CREATE TABLE LICENSE_DELEGATION (
  ID VARCHAR (64) NOT NULL,
  OWNER_ID VARCHAR (64) NOT NULL,
  LICENSE_TYPE VARCHAR (32) NOT NULL,
  PRODUCT_ID VARCHAR (64) NOT NULL,
  PRODUCT_TYPE VARCHAR (32) NOT NULL,
  TOTAL_DELEGATION_COUNT INT(11) NOT NULL,
  CREATE_USER VARCHAR (64) NOT NULL,
  CREATE_TIME BIGINT NOT NULL,
  MODIFY_USER VARCHAR (64),
  MODIFY_TIME BIGINT,
  PRIMARY KEY (PRODUCT_ID, OWNER_ID, PRODUCT_TYPE)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE DELEGATION_DETAIL (
  ID VARCHAR (64) NOT NULL,
  LICENSE_DELEGATION_ID VARCHAR (64),
  ENTITY_ID VARCHAR (64) NOT NULL,
  FULFILLED_ID VARCHAR (64) NOT NULL,
  ENTITY_TYPE VARCHAR (32) NOT NULL,
  DELEGATION_COUNT INT(11) NOT NULL,
  CREATE_USER VARCHAR (64) NOT NULL,
  CREATE_TIME BIGINT NOT NULL,
  MODIFY_USER VARCHAR(64),
  MODIFY_TIME BIGINT,
  PRIMARY KEY (ENTITY_ID, ENTITY_TYPE),
  FOREIGN KEY (LICENSE_DELEGATION_ID) REFERENCES LICENSE_DELEGATION (PRODUCT_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE HOOLIHAN_SUBSCRIPTION (
  ID VARCHAR (64) NOT NULL,
  HOOK VARCHAR (256) NOT NULL,
  TOPIC VARCHAR (64) NOT NULL,
  ACTIVE BOOLEAN,
  OFFSET BIGINT,
  `PARTITION` BIGINT,
  CREATE_TIMESTAMP BIGINT NOT NULL,
  UPDATE_TIMESTAMP BIGINT NOT NULL,
  PRIMARY KEY (TOPIC)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE HOOLIHAN_NOTIFICATION (
  ID VARCHAR (64) NOT NULL,
  OFFSET BIGINT,
  `PARTITION` BIGINT,
  CONTENT TEXT,
  TOPIC VARCHAR (64) NOT NULL,
  TIMESTAMP BIGINT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (TOPIC) REFERENCES HOOLIHAN_SUBSCRIPTION (TOPIC)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

